version: "3.7"

services:
  proxy:
    image: traefik:v2.2
    networks:
      - traefik-public
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      # from the env var TRAEFIK_TAG
      - --providers.docker.constraints=Label(`traefik.constraint-label-stack`, `dash.klh.criptofesta.org`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Enable Docker Swarm mode
      - --providers.docker.swarmmode
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable the Dashboard and API
      - --api
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        - traefik.constraint-label=traefik-public
        # traefik-http set up only to use the middleware to redirect to https
        - traefik.http.middlewares.mobdash-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.mobdash-https-redirect.redirectscheme.permanent=true
        # Handle host with and without "www" to redirect to only one of them
        # Uses environment variable DOMAIN
        # To disable www redirection remove the Host() you want to discard, here and
        # below for HTTPS
        - traefik.http.routers.mobdash-proxy-http.rule=Host(`dash.klh.criptofesta.org`) || Host(`www.dash.klh.criptofesta.org`)
        - traefik.http.routers.mobdash-proxy-http.entrypoints=http
        # traefik-https the actual router using HTTPS
        - traefik.http.routers.mobdash-proxy-https.rule=Host(`dash.klh.criptofesta.org`) || Host(`www.dash.klh.criptofesta.org`)
        - traefik.http.routers.mobdash-proxy-https.entrypoints=https
        - traefik.http.routers.mobdash-proxy-https.tls=true
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.mobdash-proxy-https.tls.certresolver=le
        # Define the port inside of the Docker service to use
        - traefik.http.services.mobdash-proxy.loadbalancer.server.port=80
        # Handle domain with and without "www" to redirect to only one
        # To disable www redirection remove the next line
        - traefik.http.middlewares.mobdash-www-redirect.redirectregex.regex=^https?://(www.)?(dash.klh.criptofesta.org)/(.*)
        # Redirect a domain with www to non-www
        # To disable it remove the next line
        - traefik.http.middlewares.mobdash-www-redirect.redirectregex.replacement=https://dash.klh.criptofesta.org/$${3}
        # Redirect a domain without www to www
        # To enable it remove the previous line and uncomment the next
        # - traefik.http.middlewares.mobdash-www-redirect.redirectregex.replacement=https://www.dash.klh.criptofesta.org/$${3}
        # Middleware to redirect www, to disable it remove the next line
        - traefik.http.routers.mobdash-proxy-https.middlewares=mobdash-www-redirect
        # Middleware to redirect www, and redirect HTTP to HTTPS
        # to disable www redirection remove the section: mobdash-www-redirect,
        - traefik.http.routers.mobdash-proxy-http.middlewares=mobdash-www-redirect,mobdash-https-redirect

  dash:
    image: dash:$VERSION
    container_name: dash
    environment:
      - SERVER_NAME=dash.klh.criptofesta.org
      - SERVER_HOST=https://dash.klh.criptofesta.org
      - TARGET=$TARGET
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - traefik-public
    deploy:
      labels:
        - traefik.enable=true
        - traefik.constraint-label-stack=dash.klh.criptofesta.org
        - traefik.http.routers.mobdash-dash-http.rule=Host(`dash.klh.criptofesta.org`)
        - traefik.http.services.mobdash-dash.loadbalancer.server.port=8085
        - traefik.docker.network=traefik-public



networks:
  traefik-public:
    external: true
